- name: Apache installation
  hosts: node1
  become: yes
  tasks:
    - name: Install httpd
      dnf:
        name: httpd
        state: present
    - name: Enable and start service
      service:
        name: httpd
        state: started
        enabled: yes
